site_name: Navega Consultoria
site_description: Documentação da Navega Consultoria
repo_url: https://github.com/NavegaSistemas
site_dir: site
copyright: Copyright &copy; 2019, <a href="http://navegaconsultoria.com.br/">Navega Consultoria</a>.
dev_addr: ‘0.0.0.0:8000
theme:
  name: 'material'
  logo: 'images/icon.png'
  favicon: 'images/icon.png'
  palette:
    primary: 'blue'
  language: 'pt'

extra:
  social:
    - type: 'github'
      link: 'http://navegaconsultoria.com.br/'
# extra_css:
#   - 'stylesheets/extra.css'
plugins:
  - search
nav:
  - Home: 'index.md'
  - Navega:
    - API: 
      - Introdução: Navega/API/introducao.md
      - Agendas de Visitas: Navega/API/agendas_visitas.md
      - Associados: Navega/API/associados.md
      - Atendimento: Navega/API/atendimento.md
      - Contas Gerenciais: Navega/API/contas_gerenciais.md
      - Metas: Navega/API/metas.md
      - Níveis de Saldo: Navega/API/niveis_saldo.md
      - Notificações: Navega/API/notificacoes.md
      - Usuários: Navega/API/usuarios.md
    - Mobile:  
      - Backlog: Navega/Mobile/Consultoria/backlog.md
  - Atende Bem:
    - API: 
      - Introdução: Atende_bem/API/introducao.md
      - Ajuda: Atende_bem/API/ajuda.md
      - Cadastro: Atende_bem/API/cadastro.md
      - Unidades: Atende_bem/API/unidades.md
      - Senhas de atendimento: Atende_bem/API/senhas_atendimento.md
      - Usuário: Atende_bem/API/usuario.md
    - Requisitos: Atende_bem/requisitos.md
