site_name: Navega Consultoria
site_description: Documentação da Navega Consultoria
repo_url: https://github.com/alanrslima
site_dir: site
copyright: Copyright &copy; 2019, <a href="http://navegaconsultoria.com.br/">Navega COnsultoria</a>.
dev_addr: ‘0.0.0.0:8000
theme:
  name: 'material'
  logo: 'favicon.png'
  favicon: 'favicon.png'
  palette:
    primary: 'orange'
  language: 'pt'

extra:
  social:
    - type: 'github'
      link: 'http://navegaconsultoria.com.br/'
# extra_css:
#   - 'stylesheets/extra.css'
plugins:
  - search
nav:
  - Home: 'index.md'
  - API: 
    - Associados: API/associados.md
    - Atendimento: API/atendimento.md
    - Contas Gerenciais: API/contas_gerenciais.md
    - Metas: API/metas.md
    - Níveis de Saldo: API/niveis_saldo.md
    - Notificações: API/notificacoes.md
    - Usuários: API/usuarios.md
  - Mobile: 
    - CheckList: Mobile/check_list.md
    - Dúvidas: Mobile/doubts.md


markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
